[registries.crates-io]
protocol = "sparse"

[profile.release]
panic = "abort"
opt-level = 2
strip = true
lto = true
codegen-units = 1

[build]
rustflags = [
    "-Ctarget-cpu=generic",
    "-Ctarget-feature=+crt-static",
]
