pub static FORMAT: [&str; 6] = [
    "COFF", //
    "ELF",
    "Mach-O",
    "PE",
    "Wasm",
    "XCOFF",
];

pub static ARCHITECTURE: [&str; 36] = [
    "",
    "AArch64",
    "AArch64 (ILP32 ABI)",
    "Alpha",
    "ARM 32-bit",
    "AVR",
    "BPF",
    "C-SKY",
    "Elbrus 2000 32-bit",
    "Elbrus 2000 64-bit",
    "i386",
    "x86-64",
    "x86-64 (x32 ABI)",
    "Hexagon",
    "PA-RISC",
    "LoongArch 32-bit",
    "LoongArch 64-bit",
    "Motorola 68000",
    "MIPS 32-bit",
    "MIPS 64-bit",
    "MIPS 64-bit (N32 ABI)",
    "MSP430",
    "PowerPC 32-bit",
    "PowerPC 64-bit",
    "RISC-V 32-bit",
    "RISC-V 64-bit",
    "s390x",
    "SBF",
    "SHARC",
    "SPARC",
    "SPARC V8+",
    "SPARC64",
    "SuperH",
    "WebAssembly 32-bit",
    "WebAssembly 64-bit",
    "Xtensa",
];
